# send_group_notice_plugin - 自动生成的配置文件
# 群聊发布公告管理插件，提供智能发布公告功能

# 插件基本信息配置
[plugin]
# 是否启用插件
enabled = true
# 配置文件版本
config_version = "0.0.1"

# 组件启用控制
[components]
# 是否启用智能发布公告Action
enable_smart_notice = true
# 是否启用发布公告命令Command（调试用）
enable_notice_command = true

# 权限管理配置
[permissions]
# 允许使用发布公告命令的用户列表，格式：['platform:user_id']，如['qq:123456789']。空列表表示不启用权限控制
allowed_users = ['qq:2367677516']
# 允许使用发布公告动作的群组列表，格式：['platform:group_id']，如['qq:987654321']。空列表表示不启用权限控制
allowed_groups = []

# 核心发布公告功能配置
[notice]
# 是否启用人性化的消息显示
enable_message_formatting = true
# 是否记录发布公告历史（未来功能）
log_notice_history = true
# 成功发布公告后发送的随机消息模板
templates = ['已发布群公告：{content}，理由：{reason}', '公告发布完成：{content}，原因：{reason}']
# 执行发布公告过程中发生错误时发送的随机消息模板
error_messages = ['没有指定公告内容呢~', '公告内容太长啦，不能超过1000个字符哦~', '发布公告时出现问题~']

# 智能发布公告Action的专属配置
[smart_notice]
# LLM判定的严格模式
strict_mode = true
# 关键词激活的敏感度
# 可选值: low, normal, high
keyword_sensitivity = "high"
# 是否允许并行执行（暂未启用）
allow_parallel = false

# 发布公告命令Command的专属配置
[notice_command]
# 最大批量发布公告数量（未来功能）
max_batch_size = 5
# 命令冷却时间（秒）
cooldown_seconds = 1

# 日志记录相关配置
[logging]
# 日志记录级别
# 可选值: DEBUG, INFO, WARNING, ERROR
level = "INFO"
# 日志记录前缀
prefix = "[SendGroupNoticePlugin]"
# 日志中是否包含用户信息
include_user_info = true
# 日志中是否包含操作信息
include_action_info = true
